spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/equipmentmanage?characterEncoding=utf-8


  redis:
    port: 6379
    host: localhost


  mail:
    host: smtp.qq.com
    username: 1035117515@qq.com
    password: siajjhfnmlhjbeah
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.hbsi.entity




